version: "3"
services:      
    #Context Broker


    mongo:
        image: mongo:3.4
        command: --nojournal

    ### Proxy for Context Broker ###
    ngsiproxy:
        image: fiware/ngsiproxy:latest
        ports:
            - 3000:3000

    ### Context Broker ###
    orion:
        image: fiware/orion
        depends_on:
            - mongo
            - ngsiproxy
        ports:
            - 1026:1026
        command:
            -dbhost mongo -corsOrigin __ALL -inReqPayloadMaxSize 2097152

    csvread:
        restart: always
        image: readcsv:v1
        build:
            dockerfile: Dockerfile
            context: .
        volumes:
            #- path on the host : path inside the container
            - $PWD/app-vol:/app
        environment:
            - FIWAREHOST=orion
        ports: 
            - "39002:39002"



